name: flutter_windows
description: Native Windows functionality for Flutter apps.
version: 0.0.1
homepage: https://github.com/jakerieger/flutter_windows

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: any
  win32: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
